// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChkM0olNt49vNcsXbvXwdQjLwjWXU_m2A',
    appId: '1:1067285558220:web:8ef21c9444ed4a7b81e369',
    messagingSenderId: '1067285558220',
    projectId: 'egold-c510a',
    authDomain: 'egold-c510a.firebaseapp.com',
    storageBucket: 'egold-c510a.appspot.com',
    measurementId: 'G-68CKQFDZD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC332ukBAv2u3Cd7WauneWqnZbid8qdTsY',
    appId: '1:1067285558220:android:d7631bbd60534de381e369',
    messagingSenderId: '1067285558220',
    projectId: 'egold-c510a',
    storageBucket: 'egold-c510a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtvjBZ34B2q2MoIGtES9htm_vqabtiBBA',
    appId: '1:1067285558220:ios:e3903d04c1e06fb281e369',
    messagingSenderId: '1067285558220',
    projectId: 'egold-c510a',
    storageBucket: 'egold-c510a.appspot.com',
    iosBundleId: 'com.example.eGold',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtvjBZ34B2q2MoIGtES9htm_vqabtiBBA',
    appId: '1:1067285558220:ios:e3903d04c1e06fb281e369',
    messagingSenderId: '1067285558220',
    projectId: 'egold-c510a',
    storageBucket: 'egold-c510a.appspot.com',
    iosBundleId: 'com.example.eGold',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChkM0olNt49vNcsXbvXwdQjLwjWXU_m2A',
    appId: '1:1067285558220:web:fe375fb4594b29f481e369',
    messagingSenderId: '1067285558220',
    projectId: 'egold-c510a',
    authDomain: 'egold-c510a.firebaseapp.com',
    storageBucket: 'egold-c510a.appspot.com',
    measurementId: 'G-T7LJTDQV47',
  );
}
